#!/bin/bash

# Exit on error
set -e

# Update packages
echo "Updating system..."
sudo yum update -y

# Enable and install Amazon Corretto 11 (Java 11)
echo "Installing Java 11 (Amazon Corretto)..."
sudo yum install java-11-amazon-corretto -y

# Download and extract Tomcat
echo "Downloading Tomcat..."
wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.105/bin/apache-tomcat-9.0.105.tar.gz
tar -zxvf apache-tomcat-9.0.105.tar.gz

# Rename directory
mv apache-tomcat-9.0.105 apache

# Remove access restriction in context.xml
echo "Updating context.xml..."
cd apache/webapps/manager/META-INF/
sudo sed -i '21,22d' context.xml

# Add user roles in tomcat-users.xml
echo "Configuring tomcat-users.xml..."
cd ../../../conf/
sudo sed -i '/<\/tomcat-users>/i\
  <role rolename="manager-gui"/>\n\
  <role rolename="manager-script"/>\n\
  <user username="tomcat" password="123456" roles="manager-gui,manager-script"/>' tomcat-users.xml

# Start Tomcat
echo "Starting Tomcat..."
cd ../bin/
chmod +x startup.sh
./startup.sh
